apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
      - name: blog-app
        image: skstudies/blog-website:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: $(MONGODB_URI)
        - name: JWT_SECRET
          value: $(JWT_SECRET)
# Add an echo command to print the values of the environment variables
- script: |
    echo "MONGODB_URI: $(MONGODB_URI)"
    echo "JWT_SECRET: $(JWT_SECRET)"
  displayName: 'Print environment variables'

