apiVersion: v1
kind: Secret
metadata:
  name: blog-app-secrets
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9icmF2ZXVua25vd24xMjM6aFh0bW1KYVlPTWJpRlQ2MEBjbHVzdGVyMC5uZGR3NnBsLm1vbmdvZGIubmV0L2Jsb2c=
  JWT_SECRET: TXlTZWNyZXRCbG9n
